# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86c72a61fb9d21c13bb50d97159fd9e9eaacf33c30894f0fff924f266199e01a60d328d161e89823c835766725a4f745c9f85e91a747cf7a70a2dfe463947e2a

test:
  secret_key_base: 934c442e27e29e24ec42864653a5f7bd4ce1a7cdf1a0fb19589badaa5a58936f9b391c521cc686128352445e5cd573a189e78167041a5a09e4db520a06e2f9a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
